### ISSUE TITLE
[BookNote] CSR / SSR

### ISSUE THREAD

**Issue by soryeongk** [TeamBookTez/nextjs-book-stairs#12]
추가 제안사항은 아래 comment로 남겨주세요 !

## 체크리스트

- [x] 동적 라우팅
  ![image](https://user-images.githubusercontent.com/47105088/174014558-29875482-4d44-45f1-8ef6-eea46c851372.png)
- [x] common header 구현
- [x] 나가기 팝업창 (PopUpExit) 구현
- [x] 우측 모달 구현
- [x] 뒤로가기 방지
- [x] 스텝업 팝업창 구현
- [x] pre note 구현
  - [x] navigation 구현
  - [x] 저장하기 구현
  - [x] 질문 1-2
  - [x] 질문 3
  - [x] post 구현
    - [x] ableGoPeri
    - [ ] flushSync (페리 노트 구현 후 navigating 확인)
    - [x] any
- [ ] peri note 구현 (디바운싱 -> [useDeferredValue](https://velog.io/@katanazero86/React-18-%EC%97%90%EC%84%9C-%EB%8B%AC%EB%9D%BC%EC%A7%80%EB%8A%94%EC%A0%90))
- [ ] _bookcase/cardSection/BookCard.tsx_ 에서의 router.push url 고민
- [ ] SWR 및 커스텀 훅 리팩토링
- [ ] 독서 완료 페이지 --> SSR

**Comment by soryeongk** [comment]
7월 규민이 예약ㅎ

**Comment by soryeongk** [comment]
엇 이거 id 값을 isbn으로 쓰려는걸까욤?! 정확히는 책 id가 아니라 reviewId라서 다른 워딩이 더 좋을지도! isbn으로 구분되는 것이 아니라 유저의 reviewId로 구분!

**Comment by joohaem** [comment]
@soryeongk 
> 엇 이거 id 값을 isbn으로 쓰려는걸까욤?! 정확히는 책 id가 아니라 reviewId라서 다른 워딩이 더 좋을지도! isbn으로 구분되는 것이 아니라 유저의 reviewId로 구분!

앗차차 수정할게욥

**Comment by soryeongk** [comment]
book-note/{reviewId}/pre
book-note/{reviewId}/peri
book-note/{reviewId}/detail-book-note

이런 식일까요?!
이 북노트가 추후 공유될 때를 생각했을 때, 남들에게 공유되는 url은 `book-note/{reviewId}` 또는 `book-note/{reviewId}/post`로 하면 어떨까요? 작업 중에 pre / peri를 중첩라우팅이 아닌 하나의 페이지로 관리하게 된다면 edit이 들어가도 좋을 것 같아요!(예: `book-note/{reviewId}/edit`) 페이지를 나눈 것에 자꾸 의심이드는 이유는.. 사실 하나의 책에 대한 같은 일을 하는데, 페이지가 나뉘면서 임시 저장의 로직이 계속 꼬였던 것 같아서! 리팩토링하면서 중첩라우팅을 나누지 않는 것도 생각해보면 좋겠다는 생각..이 이제야 정리되었어여!

**Comment by joohaem** [comment]
@soryeongk 

아 url 안나눌 생각입니다 !
위 업데이트 된 사진 확인해주세요 !!

**Comment by soryeongk** [comment]
뀼! 벌써 업뎃이라니! 감쟈감쟈

예시 url도 book-note/example이면 어떨까윰
