### ISSUE TITLE
[Refactor] 리팩토링하고싶은거

### ISSUE THREAD

**Issue by soryeongk** [TeamBookTez/nextjs-book-stairs#22]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [ ] Refactor (리모델링 재개발)
- [ ] Fix (내가 해결해주지)
- [ ] Bug (삐용삐용 큰일 났어 / 질문)
- [ ] Feature (제가 해냈습니다)

## 내용

-

## 체크리스트

- [ ] 서재 index, fromSt, pathkey 다 string(pathKey)로 통일

**Comment by joohaem** [comment]
위 PR에 해당 사항 반영하였습니다 !
