### ISSUE TITLE
[Version upgrade] React 18로의 업그레이드

### ISSUE THREAD

**Issue by soryeongk** [TeamBookTez/nextjs-book-stairs#34]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [ ] Refactor (리모델링 재개발)
- [ ] Fix (내가 해결해주지)
- [ ] Bug (삐용삐용 큰일 났어 / 질문)
- [x] Feature (제가 해냈습니다)

## 내용

- CRA 버전에서 사용한 useDeferredValue를 사용하려면 react18로 업그레이드가 필요합니다. CRA 버전에서의 업그레이드 관련 커밋을 참고해도 좋습니다. :)) 북노트 독서중에서 사용됩니다.

## 체크리스트

- [x] react18로 업그레이드
- [x] useDeferredValue() 사용 가능한지 테스트

**Comment by Gyuminn** [comment]
마무리 하였습니다!
