### ISSUE TITLE
[Hotfix/BookNote] 재귀 컴포넌트 버그

### ISSUE THREAD

**Issue by soryeongk** [TeamBookTez/nextjs-book-stairs#55]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [ ] Refactor (리모델링 재개발)
- [ ] Fix (내가 해결해주지)
- [ ] Bug (삐용삐용 큰일 났어 / 질문)
- [ ] Feature (제가 해냈습니다)

## 내용

- 진짜 왜이러냐.. 도라버림

## 체크리스트

- [ ] 꼬리질문의 중간에서 엔터를 누르면 마지막 내용이 복사된 채로 칸이 추가되는 문제
- [ ] getNodeByPath의 로직상 문제인지는 모르겠지만 큰 질문이던, 작은 질문이던 꼬리질문에서도 답변을 생성시켰다가 지우고, 중간에서 다시 엔터를 눌렀을 경우 node가 undefined 되면서 터지는 문제
- [ ] 독서 중에서 저장하기를 누르고 새로고침을 했을 때, 독서 전으로 넘어가지고 다시 독서 중으로 돌아오면 내용이 사라져 있음. 즉 저장기능 안됨.
- [ ] 큰 질문의 답변이 여러 개일 경우 중간 답변에서 엔터를 눌렀을 때, 사이에 답변이 생성되는것 뿐만 아니라 마지막 답변에 개행이 들어감.
- [ ] 독서 전에서 큰 질문을 두 개 이상 입력하고 독서 중으로 넘어왔을 경우, 커서가 첫 번째 큰 질문의 답변에 있는게 아니라 마지막에 있음

**Comment by Gyuminn** [comment]
북노트 전체적으로 보고 있습니다.
