### ISSUE TITLE
[Hotfix/PreNote] 처음 작성하는건데 질문리스트 추가 버튼들이 사라짐ㅁ..

### ISSUE THREAD

**Issue by soryeongk** [TeamBookTez/nextjs-book-stairs#56]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [ ] Refactor (리모델링 재개발)
- [ ] Fix (내가 해결해주지)
- [ ] Bug (삐용삐용 큰일 났어 / 질문)
- [ ] Feature (제가 해냈습니다)

## 내용

- 아래 이미지 참고 - 원래는 아직 한 번도 작성하지 않은 리뷰(reviewSt가 2)에 대해서는 독서 전 질문리스트에서 질문 추가 및 삭제가 가능해야함
<img width="1704" alt="image" src="https://user-images.githubusercontent.com/40630964/183230240-ef729fb3-b7f2-49d0-85fb-95afbf869378.png">

## 체크리스트

- [ ] 처음 작성하는 유저에 대해서 질문 추가/삭제가 보여야함
- [ ] 최초 작성의 경우 그 내용이 독서 중으로 넘어가야함

**Comment by joohaem** [comment]
후에 문제 있으면 다시 찾아주세요!
