### ISSUE TITLE
[REFACTOR] 북노트 리팩토링

### ISSUE THREAD

**Issue by leeJooHaem** [TeamBookTez/nextjs-book-stairs#66]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [x] Refactor (리모델링 재개발)
- [ ] Fix (내가 해결해주지)
- [ ] Bug (삐용삐용 큰일 났어 / 질문)
- [ ] Feature (제가 해냈습니다)

## 해결하고자 하는 내용 (What & Why)

- 비즈니스 로직 더더 분리해보기
- QAInput state 제거하기

**Comment by joohaem** [comment]
https://github.com/TeamBookTez/nextjs-book-stairs/pull/68
